services:
  - type: web
    name: mp4-to-mp3
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.9"
      - key: PYTHONUNBUFFERED
        value: "1"
